### ISSUE TITLE
Python executable missing from nodejs-10 UBI image

### ISSUE THREAD

**Issue by btl5037** [IBM/nodejs-express-app#31]
While trying to build the CF app, the `npm install` fails due to the fact python is not installed in the image and thus it can't perform node-gyp tasks that require compiling from source. The previous CF nodejs app used the official nodejs image which had python installed in it. This is a huge problem and will break almost any app whose deps require being built from source through npm. You can reach me internally at IBM, Brett Logan to answer any questions.

```Executing docker image build --file Dockerfile --tag
<tag_redacted> --rm --pull .
Waiting for Docker image to build
Sending build context to Docker daemon    469kB
Step 1/12 : FROM registry.access.redhat.com/ubi8/nodejs-10
latest: Pulling from ubi8/nodejs-10
Digest: sha256:a4cf131cc6d74235e82f7ae877f9d3c2300adea8715388457b63233b4a6ce703
Status: Image is up to date for registry.access.redhat.com/ubi8/nodejs-10:latest
 ---> 16b3f1306f73
Step 2/12 : WORKDIR /app
 ---> Using cache
 ---> 1817b9cd280c
Step 3/12 : USER root
 ---> Using cache
 ---> 8ee1fd1906a0
Step 4/12 : COPY --chown=1001:1001 package.json /app/
 ---> Using cache
 ---> 18a37f4864e4
Step 5/12 : RUN cd /app
 ---> Using cache
 ---> 57b750beaee7
Step 6/12 : RUN npm install --production
 ---> Running in 16600ecad2cf
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> @ampretia/x509@0.4.7 install /app/node_modules/@ampretia/x509
> node-gyp rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 4.15.0-74-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/@ampretia/x509
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ampretia/x509@0.4.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ampretia/x509@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2020-01-14T22_53_14_897Z-debug.log
The command '/bin/sh -c npm install --production' returned a non-zero code: 1
FAILED
An error exit status 1 was encountered while building the Docker
image.
exit status 1```

**Comment by btl5037** [comment]
Spoke with the CF team, adding a line to the Dockerfile to add python should resolve this problem. Thanks you team

**Comment by answerquest** [comment]
@lindluni can you please tell what is that line to add to the Dockerfile to add python??

**Comment by lindluni** [comment]
If installing python2

```
USER root
RUN microdnf install python2
USER 1001
```

If install python3 you would also need to symlink python3 to the `python` command
